name: deploy
on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, labeled]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.actor: ${{ github.actor }}"
  deploy-prod:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: |
          echo "deploy-prodはmainにマージされたときだけ回れ"
  deploy-sandbox:
    if: |
      (
        github.event_name == 'pull_request'
        && github.event.action == 'synchronize'
      )
      ||
      (
        github.event_name == 'pull_request'
        && github.event.action == 'labeled'
        && github.event.label.name == 'deploy-sandbox'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub context
        run: |
          echo "deploy-sandbox 回ってますがな"